### ISSUE TITLE
step-1 

### ISSUE THREAD

**Issue by jfyear1994** [Lobos/react-example#1]
第一步结束前的

console下执行

$ node_module/.bin/webpack

这是什么意思   在那里执行啊，没搞懂 @Lobos

**Comment by Lobos** [comment]
呃，有很多名称，终端，cmd，shell，命令行...

**Comment by jfyear1994** [comment]
。。。后面的名称都知道，就是那个console没搞明白，我还以为是浏览器的console。。。
