### ISSUE TITLE
大哥，你的运行项目的命令是啥？

### ISSUE THREAD

**Issue by yufengkz** [Lobos/react-example#2]
大哥，你的运行项目的命令是啥？

**Comment by Lobos** [comment]
```
node server.js
```

**Comment by busyzz-1994** [comment]
你的项目 直接 npm install 为什么会报错啊
Error: EISDIR: illegal operation on a directory, symlink 'E:\react-github\react-example-master\node_modules\._classnames@2.2.5@classnames' -> 'E:\react-github\react-example-master\node_modules\classnames'
    at Error (native)

**Comment by Lobos** [comment]
你的npm版本是多少？新建一个空项目，执行一下 npm install classnames 看看，或者参考下这个问题 https://stackoverflow.com/questions/34959038/npm-stuck-giving-the-same-error-eisdir-illegal-operation-on-a-directory-read-a

**Comment by wjun52** [comment]
node server.js后报错
qenya server running on http://localhost:3002
server running on http://localhost:3000
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND localhost
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:95:26)

**Comment by Lobos** [comment]
@guanren 看下你的hosts，是不是没有 127.0.0.1 localhost
