### ISSUE TITLE
node server

### ISSUE THREAD

**Issue by Hanck97** [Lobos/react-example#3]
E:\Projects\Code-Fronted\WebProject\react-example>node server.js
E:\Projects\Code-Fronted\WebProject\react-example\server.js:60
router.get('/', async function (ctx) {
                ^^^^^
SyntaxError: missing ) after argument list
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:528:28)

**Comment by Lobos** [comment]
node的版本是什么？

**Comment by HancockTong** [comment]
v6.3.2

**Comment by Hanck97** [comment]
v6.9.2

**Comment by Lobos** [comment]
node的版本有点低，因为这个demo用了koa2做服务端，为了简单，没有给sever配置babel，需要node v7.6.0以上版本，或者自己在server启动里面加上babel配置

**Comment by Hanck97** [comment]
还是报错的
